version: '3'
services:
  streama:
    image: anapsix/alpine-java:8
    restart: unless-stopped
    volumes:
    - /streama/docker/streama-1.10.4.jar:/app/app.jar
    - ./streama/docker/application.yml:/app/application.yml
    - ./streama/volumes/uploads:/app/uploads
    - ./streama/volumes/local-files:/app/local-files
    working_dir: /app
    command: java -jar app.jar
    network_mode: "host"
    environment:
    - VIRTUAL_HOST=localhost
    #ports:
    #- "80:80"
