version: '3.7'
services:
  openldap:
    image: osixia/openldap:latest
    restart: unless-stopped
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - /mnt/efs/ctfoco/data/certificates:/container/service/slapd/assets/certs
      - /mnt/efs/ctfoco/data/slapd/database:/var/lib/ldap
      - /mnt/efs/ctfoco/data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=g2cloud
      - LDAP_DOMAIN=g2cloud.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=admin
      - "LDAP_BASE_DN=dc=g2cloud,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=g2cloud.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "8096:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

networks:
  openldap:
    driver: bridge